// Copyright (C) 2026 SALTWOOD and contributors
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AraonMC.SourceGenerators;

/// <summary>
///     Emits an internal <c>Secrets</c> class whose constants are baked in from MSBuild properties at
///     compile time. Gated by <c>&lt;AraonMCGenerateSecrets&gt;true&lt;/AraonMCGenerateSecrets&gt;</c> so
///     only the consuming app receives it; constants are empty strings when their property is unset.
///     <para>
///         Each entry maps a generated constant name to a <c>build_property.*</c> analyzer-config option
///         (itself surfaced from an environment variable via <c>&lt;CompilerVisibleProperty&gt;</c> in the
///         app's csproj). To add a new secret, append a row to <see cref="SecretDefs"/>.
///     </para>
/// </summary>
[Generator]
public sealed class SecretsSourceGenerator : IIncrementalGenerator
{
    private const string GenerateSecretsProperty = "build_property.AraonMCGenerateSecrets";

    /// <summary>
    ///     The secrets to emit. <c>ConstName</c> is the C# identifier on the <c>Secrets</c> class;
    ///     <c>BuildProperty</c> is the <c>build_property.*</c> analyzer-config option; <c>EnvVar</c> is the
    ///     human-facing environment-variable name (for doc comments); <c>Description</c> is the XML doc summary.
    /// </summary>
    private static readonly (string ConstName, string BuildProperty, string EnvVar, string Description)[] SecretDefs =
    {
        ("MsOAuthClientId", "build_property.PCL_MS_CLIENT_ID", "PCL_MS_CLIENT_ID",
            "The Microsoft OAuth public-client id. Set the PCL_MS_CLIENT_ID environment variable before building; empty when unset (the account service reports a configuration error)."),
        ("CurseForgeApiKey", "build_property.PCL_CURSEFORGE_API_KEY", "PCL_CURSEFORGE_API_KEY",
            "The CurseForge Core API key (request one from the CurseForge for Studios developer console). Set the CF_API_KEY environment variable before building; empty when unset (CurseForge search is disabled at runtime and Modrinth is used alone)."),
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var secrets = context.AnalyzerConfigOptionsProvider.Select((opts, _) =>
        {
            var enabled = opts.GlobalOptions.TryGetValue(GenerateSecretsProperty, out var gateRaw)
                          && bool.TryParse(gateRaw, out var gate) && gate;
            if (!enabled) return (Enabled: false, Values: new Dictionary<string, string>());

            var values = new Dictionary<string, string>();
            foreach (var def in SecretDefs)
            {
                opts.GlobalOptions.TryGetValue(def.BuildProperty, out var v);
                values[def.ConstName] = v ?? string.Empty;
            }
            return (Enabled: true, Values: values);
        });

        context.RegisterSourceOutput(secrets, (spc, data) =>
        {
            if (!data.Enabled) return;
            spc.AddSource("Secrets.Generated.g.cs", Emit(data.Values));
        });
    }

    private static string Emit(IReadOnlyDictionary<string, string> values)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace AraonMC;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Compile-time secrets. Values are read from MSBuild properties (each sourced from a");
        sb.AppendLine("///     build-environment variable, e.g. PCL_MS_CLIENT_ID, CF_API_KEY) by the source generator");
        sb.AppendLine("///     at build time, then baked in as constants.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class Secrets");
        sb.AppendLine("{");
        foreach (var def in SecretDefs)
        {
            var value = values.TryGetValue(def.ConstName, out var v) ? v : string.Empty;
            sb.Append("    /// <summary>");
            // Keep each doc line on its own <para> for readability.
            foreach (var line in def.Description.Split('\n'))
                sb.AppendLine().Append("    /// ").Append(line.Trim());
            sb.AppendLine();
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public const string {def.ConstName} = {EmitStringLiteral(value)};");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    ///     Produces a C# string literal, escaping backslash and double-quote. These values are opaque ASCII
    ///     tokens (client ids / API keys), so no need to handle exotic whitespace/control characters.
    /// </summary>
    private static string EmitStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            if (c == '\\' || c == '"') sb.Append('\\');
            sb.Append(c);
        }
        sb.Append('"');
        return sb.ToString();
    }
}
