// Copyright (C) 2026 SALTWOOD and contributors
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using AraonMC.Core.Domain.Entities;

namespace AraonMC.Core.Config;

/// <summary>
/// A typed accessor for an <see cref="ConfigScope.Instance"/>-scoped key. Indexing by a
/// <see cref="MinecraftInstance"/> reads/writes the value stored under that instance's
/// absolute path. Generated by the source generator as <c>Config.Section.Key[instance]</c>.
/// </summary>
public sealed class InstanceKey<T>
{
    private readonly IConfigStore _store;
    private readonly ConfigScope _scope;
    private readonly string _path;
    private readonly T? _default;

    public InstanceKey(IConfigStore store, ConfigScope scope, string path, T? @default)
    {
        _store = store;
        _scope = scope;
        _path = path;
        _default = @default;
    }

    /// <summary>Read/write this key for <paramref name="instance"/> (keyed by its absolute path).</summary>
    public T? this[MinecraftInstance instance]
    {
        get => _store.Get(_scope, _path, _default, instance.Path);
        set => _store.Set(_scope, _path, value, instance.Path);
    }
}
